name: Setup Clojure Project
description: Common setup for Clojure CI workflows (Java, Leiningen, tooling)

runs:
  using: composite
  steps:
    - name: Prepare Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version-file: .java-version

    - uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-lein-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-lein-

    - name: Install Clojure tools
      uses: DeLaGuardo/setup-clojure@13.4
      with:
        lein: latest
        clj-kondo: latest
        cljstyle: latest
